name: servana
description: An AI-powered task marketplace for Sri Lanka.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # --- Firebase & Core ---
  firebase_core: ^3.15.0
  firebase_auth: ^5.6.1
  cloud_firestore: ^5.6.10
  firebase_storage: ^12.4.8
  firebase_messaging: ^15.2.8
  firebase_app_check: ^0.3.2+8

  # --- AI & Services ---
  google_generative_ai: ^0.4.3
  flutter_dotenv: ^5.1.0

  # --- UI & Theming ---
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.6
  intl: ^0.20.2
  percent_indicator: ^4.2.3
  flutter_animate: ^4.5.0

  # --- Device & Location ---
  google_maps_flutter: ^2.7.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  image_picker: ^1.1.2

  # --- Utilities & State Management ---
  url_launcher: ^6.3.1
  flutter_local_notifications: ^19.3.0
  provider: ^6.1.2
  lottie: ^3.1.2
  speech_to_text: ^7.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/Gemini_Generated_Image.png
    - .env
    - assets/animations/
